---
abstract: 'Redis client specialized for cache'
author:
  - 'Masayuki Matsuki E<lt>y.songmu@gmail.comE<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0.06
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cache-Redis
no_index:
  directory:
    - inc
provides:
  Cache::Redis:
    file: lib/Cache/Redis.pm
    version: 0.02
requires:
  Data::MessagePack: 0.36
  Redis: 0
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
