---
abstract: 'Redis client specialized for cache'
author:
  - 'Masayuki Matsuki <y.songmu@gmail.com>'
build_requires:
  Test::More: 0.98
  Test::RedisServer: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.2, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cache-Redis
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Cache::Redis:
    file: lib/Cache/Redis.pm
    version: 0.05
requires:
  Data::MessagePack: 0.36
  Redis: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/Songmu/p5-Cache-Redis/issues
  homepage: https://github.com/Songmu/p5-Cache-Redis
  repository: git://github.com/Songmu/p5-Cache-Redis.git
version: 0.05
